[package]
name = "llvm-ir"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"
description = "LLVM IR in natural Rust data structures"
documentation = "https://docs.rs/llvm-ir"
repository = "https://github.com/cdisselkoen/llvm-ir"
readme = "README.md"
keywords = ["llvm", "ir"]
license = "MIT"

[dependencies]
llvm-sys = "~80.1.1"
either = "1.5.2"
log = "0.4.0"
libc = "0.2"

[dev-dependencies]
env_logger = "0.6.2"
